# Generated by Django 4.0.3 on 2022-03-28 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('num_errors', models.IntegerField()),
                ('num_items', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zyte.spider')),
            ],
        ),
    ]
